#!/bin/bash

# Ensure the daemon is run as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run daemon as root"
  exit 1
fi

# Check if the application directory exists
if [ ! -d "/opt/vdtg-rmm" ]; then
  echo "Application not installed at /opt/vdtg-rmm. Please install application in the correct folder."
  exit 1
fi

# Move to application directory
cd /opt/vdtg-rmm || exit 1

# Reset local git changes
git reset --hard

# Pull latest code
git pull

# Make main application executable
chmod +x /opt/vdtg-rmm/bin/vdtg-rmm

# Make daemon executable
chmod +x /opt/vdtg-rmm/vdtg-rmm-daemon

# Run main application
bash /opt/vdtg-rmm/bin/vdtg-rmm
