#!/bin/bash

# Check if daemon is run as root
if [ "$EUID" -ne 0 ]
  then echo "Please run daemon as root"
  exit
fi

# Check if /opt/vdtg-rmm application folder exists else stop code execution
if [ -d "/opt/vdtg-rmm" ]
then
    
    # Move to vdtg-rmm application folder
    cd /opt/vdtg-rmm

    # Check if vdtg-rmm.config file exists else stop code execution
    if [ ! -f "vdtg-rmm.config" ]; then
        echo "Configuration file vdtg-rmm.config not found in /opt/vdtg-rmm. Exiting application."
        exit
    fi

    # Check if update_app is set to true in config file and if so, update application before running it
    update_app=$(grep -v '^#' /opt/vdtg-rmm/vdtg-rmm.config | grep -i 'update_app' | awk -F'=' '{print $2}')
    if [ "$update_app" == "true" ]; then
        echo "Updating application..."
        
        # Reset any local changes to the application code
        git reset --hard

        # Pull latest changes from the repository
        git pull
    fi

    # Make vdtg-rmm application executable
    chmod +x /opt/vdtg-rmm/bin/vdtg-rmm

    # Make vdtg-rmm daemon executable
    chmod +x /opt/vdtg-rmm/vdtg-rmm-daemon

    # Run application
    bash /opt/vdtg-rmm/bin/vdtg-rmm

else
    echo "Application not installed at /opt/vdtg-rmm. Please install application in the correct folder."
    exit
fi
