services:
  unifi-video:
    image: pducharme/unifi-video-controller
    container_name: vdtg-unifi-video
    cap_add:
      - DAC_READ_SEARCH
    ports:
      - 10001:10001
      - 1935:1935
      - 6666:6666
      - 7080:7080
      - 7442:7442
      - 7443:7443
      - 7444:7444
      - 7445:7445
      - 7446:7446
      - 7447:7447
    volumes:
      - /opt/vdtg-rmm/docker-data/unifi-video:/var/lib/unifi-video
      - /tmp/unifi-video:/var/cache/unifi-video
    environment:
      - TZ=Europe/Amsterdam
      - PUID=99
      - PGID=100
      - CREATE_TMPFS=no
      - DEBUG=1